---
title: "hantaro_scripts_01_cleaning (annotated)"
author: "Daniel Becker (annotated by Katie Tseng)"
date: "1/14/2022"
output: html_document
---

```{r setup}

## hantaro 01: rodent hantavirus cleaning
## danbeck@ou.edu

## clean environment & plots
rm(list=ls()) 
graphics.off()

## install packages
install.packages("ape")
install.packages("plyr")

## libraries
library(ape)
library(plyr)
```


```{r load hantavirus data}

## load in hantavirus data
#setwd("~/Desktop/hantaro/data/raw")
#hdata=read.csv("Muroid Taxonomy and Traits with Hantavirus #Evidence.csv",header=T)
hdata=read.csv(url("https://raw.githubusercontent.com/viralemergence/hantaro/master/data/raw/Muroid%20Taxonomy%20and%20Traits%20with%20Hantavirus%20Evidence.csv"))

## fix missing PCR studies 
hdata$X..papers.PCR.pos=ifelse(hdata$Species_Name=="Akodon_simulator",1,hdata$X..papers.PCR.pos)
hdata$X..papers.PCR.pos=ifelse(hdata$Species_Name=="Calomys_callosus",1,hdata$X..papers.PCR.pos)
# question: why were these missing and how was this data obtained as it appears to also include trait data (e.g, Virion package vroom)?

## synonym IUCN
hdata$IUCNname=hdata$Notes.regarding.IUCN.status

## load in traits
#traits=read.csv("pan for PNAS Dryad.csv",header=T)
traits=read.csv(url("https://raw.githubusercontent.com/viralemergence/hantaro/master/data/raw/pan%20for%20PNAS%20Dryad.csv"))
traits$X=NULL
# question: data extracted from Pantheria? 

## remove family 
start='Abrocomidae'
end='Thryonomyidae'
trim=which(names(traits)==start):which(names(traits)==end)
traits=traits[,-trim]
rm(trim,start,end)
# note: removes binary columns of species' family

## remove duplicates 
traits=traits[!duplicated(traits$Rodents),] 
# note: removes single duplicate, to see which element was a duplicate, run "traits=traits[duplicated(traits$Rodents),]"
```


```{r load phylogeny data}

## load Upham phylogeny
setwd("/Users/CDDEP/Downloads/OPV Host Prediction/hantaro/phylo")
#tree=read.nexus('MamPhy_fullPosterior_BDvr_Completed_5911sp_topoCons_NDexp_MCC_v2_target.tre')
tree=read.nexus(url("https://raw.githubusercontent.com/viralemergence/hantaro/master/phylo/MamPhy_fullPosterior_BDvr_Completed_5911sp_topoCons_NDexp_MCC_v2_target.tre"))
# question: plotting using 'plot(tree)' returned error

## load in taxonomy
#taxa=read.csv('taxonomy_mamPhy_5911species.csv',header=T)
taxa=read.csv(url("https://raw.githubusercontent.com/viralemergence/hantaro/master/phylo/taxonomy_mamPhy_5911species.csv"))

## simplify to genus
gtaxa=taxa[!duplicated(taxa$gen),] #note: drops duplicates at the genus level
gtaxa=gtaxa[c('gen','fam','ord','clade','higher')]
```


```{r simplifiy datasets}
## simplify datasets  #note: generates new vars of PCR+, PCR-, isolation
hdata$PCR=hdata$X..papers.PCR.pos
hdata$PCRneg=hdata$X..papers.PCR.neg..whether.seropos.or.seroneg.
hdata$isolation=hdata$X..papers.isolated

## trim
hdata=hdata[c('Species_Name','PCR','PCRneg','isolation',
              'IUCNname')]

## geography
hdata$geography='New World'

## studies
hdata$studies=rowSums(hdata[c('PCR','PCRneg','isolation')],na.rm=T) 
# note: sums values (0/1) in the row for the columns above

## hantavirus PCR
hdata$hPCR=ifelse(hdata$PCR>0,1,0)
hdata$hPCR=ifelse(is.na(hdata$hPCR),0,hdata$hPCR)

## virus isolation
hdata$competence=ifelse(hdata$isolation>0,1,0)
hdata$competence=ifelse(is.na(hdata$competence),0,hdata$competence)

## genus
hdata$gen=sapply(strsplit(as.character(hdata$Species_Name),'_'),function(x) x[1])

## combine
data=merge(hdata,gtaxa,by='gen')

## clean  
rm(taxa,hdata,gtaxa) 
# note: removes taxa, hdata, gtaxa from environment
```


```{r simplify names}
## make simple names
data$tip=data$Species_Name
tree$tip=sapply(strsplit(tree$tip.label,'_'),function(x) paste(x[1],x[2],sep='_'))
# note: splits tree$tip.label where '_' is present into multiple columns and keeps column 1 and 2

## are all hdata in tree
data$intree=ifelse(data$tip%in%setdiff(data$tip,tree$tip),
                   'missing','upham')
# note: if tree$tip chr matches data$tip chr, returns 'upham'; if no match, returns 'missing'

## are all hdata in traits
data$intraits=ifelse(data$tip%in%setdiff(data$tip,
                                         traits$Rodents),
                     'missing','traits')

## just missing names
miss=data[c('tip','IUCNname','intree','intraits')]
miss=miss[miss$intree=='missing' | miss$intraits=='missing',]
miss=miss[order(miss$intree,miss$intraits),]
# note: creates table of entries with missing/mismatched names

## export
#setwd("~/Desktop/hantaro/data/names")
setwd("/Users/CDDEP/Downloads/OPV Host Prediction/hantaro/data/names")
write.csv(miss,'hantaro name mismatch.csv')
rm(miss)

## load in revised names with Than edits
#fix=read.csv('hantaro name mismatch_edit_TM.csv',header=T)
fix=read.csv(url("https://raw.githubusercontent.com/viralemergence/hantaro/master/data/names/hantaro%20name%20mismatch_edit_TM.csv"))
# question: how were these revised?

## merge
fix=fix[c('tip','treename','traitname','proxy')]
data=merge(data,fix,by='tip',all.x=T)

## if blank, NA
data$traitname=ifelse(data$traitname=='',NA,as.character(data$traitname))
data$treename=ifelse(data$treename=='',NA,as.character(data$treename))

## if NA, tip
data$treename=ifelse(is.na(data$treename),as.character(data$tip),as.character(data$treename))

## trait name includes proxy
#data$traitname=ifelse(is.na(data$traitname),as.character(data$tip),as.character(data$traitname))
data$traitname=ifelse(data$intraits=='missing' & is.na(data$traitname),as.character(data$proxy),
                 ifelse(data$intraits=='missing' & !is.na(data$traitname),as.character(data$traitname),
                        as.character(data$tip)))
# question: Explain lines 157-160? 
```


```{r trim and clean dataset}
## simplify
data=data[c('tip','studies','hPCR','competence','gen','fam','treename','traitname')]
rm(fix)

## fix duplicates in phylogeny
set=data[c('studies','hPCR','competence','treename')]

## which treenames occur multiple times
unique(set$treename)[table(set$treename)>1]
# note: 'table(set$treename)>1' returns TRUE for treenames w/ duplicates; 'unique' prints array of those treenames 

## aggregate
set=aggregate(.~treename,set,sum)
# question: for treenames occuring mult. times, summed value for each column (e.g., studies, hPCR), but not sure how this command works - what is '.~'?

## merge with meta
set2=merge(set,data[!duplicated(data$treename),c('tip','gen','fam','treename','traitname')],all.x=T,by='treename')
# -note: merges set2 (studies, hpCR, competence) with data (tip, gen, fam, traitname), by treename
set3 = data[!duplicated(data$treename),c('tip','gen','fam','treename','traitname')]

## simplify
data=set2
rm(set,set2)

## fix binomial
data$hPCR=ifelse(data$hPCR>0,1,0)
data$competence=ifelse(data$competence>0,1,0)
```


```{r merge trait data}
## merge traits
traits$traitname=traits$Rodents
traits$trait=1  # question: purpose?
data=merge(data,traits,by='traitname',all.x=T)
rm(traits)

## fix tree
rtree=tree
rtree$tip.label=rtree$tip # note: replace species name (including suspecies) with just genus & species

## trim
#rtree=keep.tip(rtree,data$treename)
rtree=keep.tip(rtree,rtree$tip.label[rtree$tip.label%in%data$treename])
# questioN: how does 'keep.tip' work? '%in%' returns TRUE where rtree$tip.label matches data$treename (does not have to be exact match?)

## fix
rtree$tip=NULL

## fix
rtree=makeLabel(rtree)

## get ed
library(picante)
ed=evol.distinct(rtree,type='equal.splits')
# note: calculates evolutionary distinctiveness measures for a suite of species by equal splits and fair proportions; returns species score

## treename
ed$treename=ed$Species
ed$Species=NULL

## rename
ed$ed_equal=ed$w
ed$w=NULL

## merge into data
data=merge(data,ed,by='treename',all.x=T)
rm(ed)

## cleaning
data$trait=NULL

## pubmed citations
library(easyPubMed)

## function
counter=function(name){
  as.numeric(as.character(get_pubmed_ids(gsub('_','-',name))$Count))
}
citations=c()

## loop through
for(i in 1:length(data$treename)) {
  citations[i]=counter(data$treename[i])
  print(i)
}

## compile
cites=data.frame(treename=data$treename,
                 cites=citations)

## merge
data=merge(data,cites,by='treename')

## clean
rm(cites,citations,i,counter)

## export files
#setwd("~/Desktop/hantaro/data/clean files")
setwd("/Users/CDDEP/Downloads/hantaro/data/clean files")
write.csv(data,'hantaro cleaned response and traits.csv')
saveRDS(rtree,'rodent phylo trim.rds')

```

```{r including plots}
## Including Plots

#You can also embed plots, for example:
```

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
