---
title: "Vector-pathogen prediction"
author: "Katie Tseng, Dan Becker, Heather Koehler, Pilar Fernandez, Stephanie Seiphert"
output:
  pdf_document:
  latex_engine: xelatex
  toc: yes
html_document:
  fig_height: 6
  fig_width: 6
  highlight: tango
  theme: journal
---

```{r, echo=F, message=F}
knitr::opts_chunk$set(eval=F)
```

# Introduction

The following code reproduces the analysis from:

> etc.


# Clean environment and plots

```{r echo=F, message=T}
rm(list=ls()) 
graphics.off()
```

# Load required packages

```{r echo=F, message=T}
library(ape)
library(dplyr)
library(nlme)
library(tidyverse)
library(vroom)
library(treespace) #dependency XQuartz v2.7.11 (https://www.xquartz.org/releases/XQuartz-2.7.11.html); for help installing, see https://stackoverflow.com/questions/66011929/package-rgl-in-r-not-loading-in-mac-os/66127391#66127391

library(gbm);
library(ROCR);
library(vegan);
library(plyr);library(dplyr);
library(mvtnorm)
library(xtable)
library(parallel)
```

# Set working directory

```{r echo=F, message=T}
setwd("~/Library/CloudStorage/OneDrive-WashingtonStateUniversity(email.wsu.edu)/Fernandez Lab/Projects (Active)/OPV Host Prediction/GitHub/PoxHost/")
```

# Load and format data
```{r echo=F, message=T}

# 01_cleaning.R
associations <- 
taxonomy <-
phylogeny <- 
hosttraits <-
virustraits <-

```

# Aggregate at genus level

```{r echo=F, message=T}
```

# Combine PubMed citations and evolutionary distinctiveness measure

```{r echo=F, message=T}
```

# Phylogenetic analysis

```{r echo=F, message=T}

# 02_phylofactor.R

```

# Inspect and format data for inclusion in the model

```{r echo=F, message=T}

```

# 

```{r echo=F, message=T}
```

# 

```{r echo=F, message=T}
```

# 

```{r echo=F, message=T}
```

# 